name: Build Cloudstream Extensions
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Plugins
        uses: recloudstream/cs3-builder@master

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Cloudstream-Repo
          path: build/
