name: Build Cloudstream Extensions

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.5'
          cache-read-only: false

      - name: Build Plugins
        run: gradle make --parallel --build-cache

      - name: Deploy to builds branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: builds
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
